print("   1 2 3 4 5 6 7 8")
print("1 | |O| |O| |O| |O|")
print("2 |O| |O| |O| |O| |")
print("3 | |O| |O| |O| |O|")
print("4 |O| |O| |O| |O| |")
print("5 | |O| |O| |O| |O|")
print("6 |O| |O| |O| |O| |")
print("7 | |O| |O| |O| |O|")
print("8 |O| |O| |O| |O| |")
